"""empty message

Revision ID: 564bbe4f5afd
Revises: b558dd3e0c9c
Create Date: 2021-02-18 13:40:01.829986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '564bbe4f5afd'
down_revision = 'b558dd3e0c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'status_task',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('task', 'status_text',
               existing_type=mysql.VARCHAR(length=300),
               nullable=True)
    op.alter_column('task', 'top_date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'top_date',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.alter_column('task', 'status_text',
               existing_type=mysql.VARCHAR(length=300),
               nullable=False)
    op.alter_column('task', 'status_task',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
