"""empty message

Revision ID: 667e97dacd09
Revises: 
Create Date: 2021-02-10 18:56:46.180017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '667e97dacd09'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('user_name', sa.String(length=20), nullable=False),
    sa.Column('cedula_rif', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('region_state', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('url_image', sa.String(length=500), nullable=True),
    sa.Column('user_registered', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('user_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
