"""empty message

Revision ID: 94ab08059e63
Revises: 96b3449ba299
Create Date: 2021-02-10 16:20:59.798470

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '94ab08059e63'
down_revision = '96b3449ba299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('salt', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('user_name', sa.String(length=20), nullable=False))
    op.drop_index('nickname', table_name='user')
    op.create_unique_constraint(None, 'user', ['user_name'])
    op.drop_column('user', 'nickname')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', mysql.VARCHAR(length=80), nullable=False))
    op.add_column('user', sa.Column('nickname', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('nickname', 'user', ['nickname'], unique=True)
    op.drop_column('user', 'user_name')
    op.drop_column('user', 'salt')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###
