"""empty message

Revision ID: 9d28b20f158e
Revises: 
Create Date: 2021-02-19 22:00:40.554485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d28b20f158e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('last_name', sa.String(length=120), nullable=True),
    sa.Column('user_name', sa.String(length=120), nullable=False),
    sa.Column('cedula_rif', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=False),
    sa.Column('region_state', sa.String(length=120), nullable=True),
    sa.Column('municipality', sa.String(length=120), nullable=True),
    sa.Column('hashed_password', sa.String(length=120), nullable=False),
    sa.Column('salt', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('url_image', sa.String(length=500), nullable=True),
    sa.Column('user_registered', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('url'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_admin_id', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('group_url', sa.String(length=500), nullable=False),
    sa.Column('url_image', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_admin_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_url')
    )
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('method_payment', sa.String(length=120), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('coin', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('person_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('method_payment', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.String(length=120), nullable=False),
    sa.Column('bank', sa.String(length=120), nullable=False),
    sa.Column('usd_amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_task', sa.String(length=120), nullable=False),
    sa.Column('status_text', sa.String(length=300), nullable=True),
    sa.Column('status_task', sa.Boolean(), nullable=True),
    sa.Column('top_date', sa.String(length=120), nullable=True),
    sa.Column('init_date', sa.String(length=120), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('sale')
    op.drop_table('person_group')
    op.drop_table('expense')
    op.drop_table('group')
    op.drop_table('user')
    # ### end Alembic commands ###
