"""empty message

Revision ID: b558dd3e0c9c
Revises: 97cbce78533d
Create Date: 2021-02-18 02:18:04.802816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b558dd3e0c9c'
down_revision = '97cbce78533d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('description', sa.String(length=250), nullable=True))
    op.drop_column('group', 'descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('descripcion', mysql.VARCHAR(length=250), nullable=True))
    op.drop_column('group', 'description')
    # ### end Alembic commands ###
