"""empty message

Revision ID: d0ce9ed6e73f
Revises: c97a50bf8329
Create Date: 2021-02-16 19:46:56.997521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ce9ed6e73f'
down_revision = 'c97a50bf8329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('country_code', table_name='user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('country_code', 'user', ['country_code'], unique=True)
    # ### end Alembic commands ###
