"""empty message

Revision ID: fa140f1b5917
Revises: 564bbe4f5afd
Create Date: 2021-02-18 16:46:59.778656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fa140f1b5917'
down_revision = '564bbe4f5afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('user_admin_id', sa.Integer(), nullable=True))
    op.drop_column('group', 'target_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('target_time', mysql.VARCHAR(length=120), nullable=True))
    op.drop_column('group', 'user_admin_id')
    # ### end Alembic commands ###
